% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Dec-2020 20:12:36
%  MATLAB version: 9.7.0.1190202 (R2019b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

angle = saveVarsMat.angle;

clear saveVarsMat;
